name: Deploy in Production

on: 
  push:
    branches:
        - main


jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run:  npm test
        
      - name: Build Application
        run:  npm run build
